# Generated by Django 4.2.18 on 2025-02-06 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('projectID', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('projectName', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('startdate', models.DateTimeField(auto_now=True)),
                ('estimatedDuration', models.IntegerField()),
                ('projectType', models.TextField(choices=[('SW', 'Software Project'), ('RSCH', 'Research Project')], null=True)),
                ('projectLeader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
