# Generated by Django 4.1.7 on 2025-02-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='startdate',
            new_name='startDate',
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.TextField(choices=[('PL', 'planning'), ('IN', 'Initiated'), ('IP', 'In progress'), ('OH', 'On Hold')], null=True),
        ),
    ]
