# Generated by Django 4.1.7 on 2024-12-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_issueassgnmt_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueassgnmt',
            name='resolution_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
