# Generated by Django 4.2.18 on 2025-02-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_startdate_project_startdate_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.TextField(choices=[('PL', 'planning'), ('IN', 'Initiated'), ('IP', 'inProgress'), ('OH', 'On Hold')], null=True),
        ),
    ]
