# Generated by Django 4.1.7 on 2025-02-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.TextField(choices=[('P', 'planning'), ('IN', 'Initiated'), ('inProgress', 'inProgress'), ('OH', 'On Hold')], null=True),
        ),
    ]
