# Generated by Django 4.1.7 on 2024-12-11 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_alter_issueassgnmt_resolution_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='assigned_to',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
