# Generated by Django 4.1.7 on 2024-12-11 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_module_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='parent_issue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.issue'),
        ),
    ]
