# Generated by Django 4.2.18 on 2025-02-06 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0005_project_id_alter_project_projectid'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_url',
            field=models.URLField(null=True),
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctitle', models.CharField(default='sample issue', max_length=45)),
                ('ctype', models.CharField(default='software project', max_length=30)),
                ('cpriority', models.CharField(default='low', max_length=20)),
                ('ctags', models.CharField(max_length=256, null=True)),
                ('cdueDate', models.DateTimeField(null=True)),
                ('cassignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cproject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.project')),
            ],
        ),
    ]
