# Generated by Django 4.1.7 on 2024-12-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_project_end_date_project_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='expected_completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
