# Generated by Django 4.1.7 on 2024-12-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_module_expected_completion_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='parent_issue',
        ),
        migrations.AddField(
            model_name='issueassgnmt',
            name='escalated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='issueassgnmt',
            name='expected_resolution_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
