# Generated by Django 4.1.7 on 2024-12-12 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_issue_parent_issue_issueassgnmt_escalated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='can_esc',
        ),
    ]
