# Generated by Django 4.1.7 on 2024-12-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_issue_can_esc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueassgnmt',
            name='priority',
            field=models.TextField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Low', max_length=6),
        ),
        migrations.AlterField(
            model_name='issueassgnmt',
            name='status',
            field=models.TextField(choices=[('Open', 'open'), ('Pending', 'pending'), ('In progress', 'In progress'), ('Closed', 'closed')], default='Open', max_length=12),
        ),
    ]
