# Generated by Django 4.1.7 on 2024-12-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_issueassgnmt_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='raised_by',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
