# Generated by Django 4.1.7 on 2024-12-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_issue_raised_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='Type',
            field=models.CharField(choices=[('bug', 'bug'), ('FR', 'feature requuest'), ('IM', 'improvement')], max_length=20),
        ),
    ]
