# Generated by Django 4.1.7 on 2024-12-31 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_module_assigned_to_module_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='raised_by',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
